### ISSUE TITLE
Некорректная версия Selenide

### ISSUE THREAD

**Issue by Cliffart44** [netology-code/aqa-code#1]
На настоящий момент актуальная [5.15.1.](https://github.com/selenide/selenide/releases)

https://github.com/netology-code/aqa-code/blob/93b9a10786f9b6da33526d6de44928d656d0bb42/bdd/akita/build.gradle#L39

**Comment by coursar** [comment]
fixed by 5734eb65452b81d739f280d048f62e272c9dc2c4
